; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:bluepill_f103c8]
platform = ststm32
framework = cmsis
board = bluepill_f103c8

build_flags =
  -Wl,-Tld/STM32F103C8TX_FLASH_header.ld
  -D_FLASH_BASE_OFFSET=0x00000000U      ; usar en 0 
  
  ;-DUSER_VECT_TAB_ADDRESS
  ;-DVECT_TAB_OFFSET=0x00004000U         ; usar 0x00004000U cuando se ejecute como app secundaria


;build_flags =
;  -Os                      ; optimize for size (O mayúscula)
;  -ffunction-sections
;  -fdata-sections
;  -fno-exceptions
;  -Wall
;  -Wextra

